name : sac
# Configurations for Stochastic Algorithms (PPO, PPG, SAC, TQC)
log_std_bound : [-20, 2]

# SAC & TQC Configurations
temperature_lr : !!float 0.0003
n_critics : !!int 5
n_quantiles : !!int 25
n_drop_atoms : !!float 2