name : td3
# Configurations for Deterministic Algorithms (DDPG, TD3)
noise_scale : !!float 0.1
target_noise_clip : !!float 0.5
target_noise_scale : !!float 0.2

policy_update_delay : !!int 2

use_onnx : false