name : td7
noise_scale : !!float 0.1
target_noise_clip : !!float 0.5
target_noise_scale : !!float 0.2
noise_scale_annealing: !!bool false
noise_scale_annealing_max_steps: 500000
latent_obs_dim : !!int 256
target_update_steps : !!int 250

latent_state_dim : !!int 256
encoder_hidden_dims : [256, 256]
LAP_normalize_action : !!bool true
LAP_prioritized : !!bool true
LAP_alpha : !!float 0.4
encoder_lr : !!float 0.0003

policy_update_delay : !!int 2
